before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


build_image:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG


deploy_image:
  stage: production
  script:
    - curl -X POST http://cosci.be:9000/api/webhooks/5dc429ef-63f4-4e8d-89be-c47fd408d2cd
    
