name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag coscicorp/website:latest
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/coscicorp/website
          labels: latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull from GitHub package
      run: docker pull ghcr.io/coscicorp/website:latest
    - name: Re-tag image
      run: docker tag ghcr.io/coscicorp/website:latest registry.projectweek.be/cosciweb:latest
    - name: Docker Push
      run: docker push registry.projectweek.be/cosciweb:latest

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.1.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"